

/*create table test_02 (
desc1 varchar(255),
desc2 varchar(255)
)

select * from test_01
minus
select * from test_02
*/
--查询序列
--select * from user_sequences;
--merge用法
merge into mdm_wlzsh_code a
using (select * from szqmdm.mdm_wlzsh_code@mdm_to_uat2 where desc12 in(
select distinct desc12 from
(
select t1.desc12,t1.desc10,t1.desc48,t1.desc89 from szqmdm.mdm_wlzsh_code@mdm_to_uat2 t1
minus
select t2.desc12,t2.desc10,t2.desc48,t2.desc89 from mdm_wlzsh_code t2  )--两个结果一减，剩下的就是不同的 
))b
on(a.desc12 =b.desc12)--物料代码相同，说明只是属性不同，就update；如果物料代码不同，说明b.desc12是null，那就insert
when matched then
    update  set a.desc48 =b.desc48,
  a.desc10=b.desc10,
  a.desc89=b.desc89
when not matched then
  insert values(
         MDM_WLZSH_SEQ.NEXTVAL,--取下一个序列的值
         b.categorycode,
         b.categoryname,
         'C'||seq_wlzsh.nextval,
         b.desc1,
         b.desc2,
         b.desc3,
         b.desc4,
         b.desc5,
         b.desc6,
         b.desc7,
         b.desc8,
         b.desc9,
         b.desc10,
         b.assistantcode1,
         b.assistantcode2,
         b.assistantcode3,
         b.assistantcode4,
         b.mnemoniccode,
         b.desclong,
         b.descshort,
         b.parentid,
         b.recordercode,
         b.recorderdesc,
         b.recordtime,
         b.auditorcode,
         b.auditordesc,
         b.audittime,
         b.auditlevel,
         b.auditflag,
         b.retrieveflag,
         b.retrievercode,
         b.retrieverdesc,
         b.retrievetime,
         b.freezeflag,
         b.freezercode,
         b.freezerdesc,
         b.freezetime,
         b.workflowid,
         b.recordercorp,
         b.mdmcode,
         b.auditlevelname,
         b.desc11,
         b.desc12,
         b.desc13,
         b.desc14,
         b.desc15,
         b.desc16,
         b.desc17,
         b.desc18,
         b.desc19,
         b.desc20,
         b.desc21,
         b.desc22,
         b.desc23,
         b.desc24,
         b.desc25,
         b.desc26,
         b.desc27,
         b.desc28,
         b.desc29,
         b.desc30,
         b.version,
         b.syscodeversion,
         b.filingflag,
         b.filingusercode,
         b.filingusername,
         b.filingdate,
         b.lucenceflag,
         b.lucencetime,
         b.submitcorp,
         b.desc31,
         b.desc32,
         b.desc33,
         b.desc34,
         b.desc35,
         b.desc36,
         b.desc37,
         b.desc38,
         b.desc39,
         b.desc40,
         b.desc41,
         b.desc42,
         b.desc43,
         b.desc44,
         b.desc45,
         b.desc46,
         b.desc47,
         b.desc48,
         b.desc49,
         b.desc50,
         b.desc51,
         b.desc52,
         b.desc53,
         b.desc54,
         b.desc55,
         b.desc56,
         b.desc57,
         b.desc58,
         b.desc59,
         b.desc60,
         b.desc61,
         b.desc62,
         b.desc63,
         b.desc64,
         b.desc65,
         b.desc66,
         b.desc67,
         b.desc68,
         b.desc69,
         b.desc70,
         b.desc71,
         b.desc72,
         b.desc73,
         b.desc74,
         b.desc75,
         b.desc76,
         b.desc77,
         b.desc78,
         b.desc79,
         b.desc80,
         b.desc81,
         b.desc82,
         b.desc83,
         b.desc84,
         b.desc85,
         b.desc86,
         b.desc87,
         b.desc88,
         b.desc89,
         b.desc90,
         b.desc91,
         b.desc92,
         b.desc93,
         b.desc94,
         b.desc95,
         b.desc96,
         b.desc97,
         b.desc98,
         b.desc99,
         b.desc100,
         b.remark,
         b.validatemsg,
         b.modifypropertygcode,
         b.categoryversion,
         b.mdmcodecreateable,
         b.lastmodifyrecordercode,
         b.lastmodifyrecorderdesc,
         b.lastmodifyrecordtime,
         b.submittime,
         b.flowpara,
         b.filecount,
         b.tempsaveflag,
         b.taskflag,
         b.uuid,
         b.errormsg,
         b.auditingflag,
         b.releaseflag,
         b.datasourceflag,
         b.lastmodifysubmitcorp,
         b.useparentworkflow)
  
